#!/usr/bin/env node
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { createServer } from "http";
import { registerA11yFixerTools } from "./tools/a11y-fixer.js";
import { registerAlertRulesTools } from "./tools/alert-rules.js";
import { registerApiDocsTools } from "./tools/api-docs.js";
import { registerApiForgeTools } from "./tools/api-forge.js";
import { registerApiKeyManagerTools } from "./tools/api-key-manager.js";
import { registerArchitectureDocsTools } from "./tools/architecture-docs.js";
import { registerAuditTrailTools } from "./tools/audit-trail.js";
import { registerAuthArchitectTools } from "./tools/auth-architect.js";
import { registerBatchJobTools } from "./tools/batch-job.js";
import { registerBillingSystemTools } from "./tools/billing-system.js";
import { registerBundleAnalyzerTools } from "./tools/bundle-analyzer.js";
import { registerCacheArchitectTools } from "./tools/cache-architect.js";
import { registerChangelogGenTools } from "./tools/changelog-gen.js";
import { registerCircuitBreakerTools } from "./tools/circuit-breaker.js";
import { registerCliBuilderTools } from "./tools/cli-builder.js";
import { registerCloudflareWorkerTools } from "./tools/cloudflare-worker.js";
import { registerCodeSmellsTools } from "./tools/code-smells.js";
import { registerCommitLinterTools } from "./tools/commit-linter.js";
import { registerComplexityReducerTools } from "./tools/complexity-reducer.js";
import { registerContainerGuardTools } from "./tools/container-guard.js";
import { registerCostHawkTools } from "./tools/cost-hawk.js";
import { registerCoverageAnalyzerTools } from "./tools/coverage-analyzer.js";
import { registerCssOptimizerTools } from "./tools/css-optimizer.js";
import { registerDataAnonymizerTools } from "./tools/data-anonymizer.js";
import { registerDataGenTools } from "./tools/data-gen.js";
import { registerDataMapperTools } from "./tools/data-mapper.js";
import { registerDeadCodeTools } from "./tools/dead-code.js";
import { registerDepShieldTools } from "./tools/dep-shield.js";
import { registerDevcontainerTools } from "./tools/devcontainer.js";
import { registerDisasterRecoveryTools } from "./tools/disaster-recovery.js";
import { registerDistributedTracingTools } from "./tools/distributed-tracing.js";
import { registerDockerComposeGenTools } from "./tools/docker-compose-gen.js";
import { registerDotnetSetupTools } from "./tools/dotnet-setup.js";
import { registerDuplicationHunterTools } from "./tools/duplication-hunter.js";
import { registerDynamodbDesignerTools } from "./tools/dynamodb-designer.js";
import { registerE2eScenarioTools } from "./tools/e2e-scenario.js";
import { registerEmailTemplateTools } from "./tools/email-template.js";
import { registerEntitlementTools } from "./tools/entitlement.js";
import { registerEnvGuardianTools } from "./tools/env-guardian.js";
import { registerErrorBoundaryTools } from "./tools/error-boundary.js";
import { registerErrorTrackingTools } from "./tools/error-tracking.js";
import { registerEslintConfigTools } from "./tools/eslint-config.js";
import { registerEtlBuilderTools } from "./tools/etl-builder.js";
import { registerFeatureFlagTools } from "./tools/feature-flag.js";
import { registerFileStorageTools } from "./tools/file-storage.js";
import { registerFlakyTestFinderTools } from "./tools/flaky-test-finder.js";
import { registerFormBuilderTools } from "./tools/form-builder.js";
import { registerGdprToolkitTools } from "./tools/gdpr-toolkit.js";
import { registerGitWorkflowTools } from "./tools/git-workflow.js";
import { registerGithubActionsGenTools } from "./tools/github-actions-gen.js";
import { registerGoScaffoldTools } from "./tools/go-scaffold.js";
import { registerGraphqlBuilderTools } from "./tools/graphql-builder.js";
import { registerGraphqlClientTools } from "./tools/graphql-client.js";
import { registerHelmChartTools } from "./tools/helm-chart.js";
import { registerHttpClientTools } from "./tools/http-client.js";
import { registerI18nExtractorTools } from "./tools/i18n-extractor.js";
import { registerIacScannerTools } from "./tools/iac-scanner.js";
import { registerImagePipelineTools } from "./tools/image-pipeline.js";
import { registerJavaSpringTools } from "./tools/java-spring.js";
import { registerJobDashboardTools } from "./tools/job-dashboard.js";
import { registerJobQueueTools } from "./tools/job-queue.js";
import { registerJsonToTypesTools } from "./tools/json-to-types.js";
import { registerJsonTransformerTools } from "./tools/json-transformer.js";
import { registerJwtToolkitTools } from "./tools/jwt-toolkit.js";
import { registerK8sManifestTools } from "./tools/k8s-manifest.js";
import { registerLambdaBuilderTools } from "./tools/lambda-builder.js";
import { registerLogSleuthTools } from "./tools/log-sleuth.js";
import { registerMakefileGenTools } from "./tools/makefile-gen.js";
import { registerMonitoringStackTools } from "./tools/monitoring-stack.js";
import { registerMultiTenantTools } from "./tools/multi-tenant.js";
import { registerNginxConfigTools } from "./tools/nginx-config.js";
import { registerNodeExpressTools } from "./tools/node-express.js";
import { registerNodeNestjsTools } from "./tools/node-nestjs.js";
import { registerNotifyHubTools } from "./tools/notify-hub.js";
import { registerOauthSetupTools } from "./tools/oauth-setup.js";
import { registerOpenapiCodegenTools } from "./tools/openapi-codegen.js";
import { registerOwaspCheckerTools } from "./tools/owasp-checker.js";
import { registerPaginationGenTools } from "./tools/pagination-gen.js";
import { registerPasskeySetupTools } from "./tools/passkey-setup.js";
import { registerPerfPilotTools } from "./tools/perf-pilot.js";
import { registerPinoSetupTools } from "./tools/pino-setup.js";
import { registerPipelineOpsTools } from "./tools/pipeline-ops.js";
import { registerPresignedUrlsTools } from "./tools/presigned-urls.js";
import { registerPricingPageTools } from "./tools/pricing-page.js";
import { registerProjectInitTools } from "./tools/project-init.js";
import { registerProtobufGenTools } from "./tools/protobuf-gen.js";
import { registerPushNotificationTools } from "./tools/push-notification.js";
import { registerPwaBuilderTools } from "./tools/pwa-builder.js";
import { registerPythonDjangoTools } from "./tools/python-django.js";
import { registerPythonFastapiTools } from "./tools/python-fastapi.js";
import { registerPythonSetupTools } from "./tools/python-setup.js";
import { registerQueryOptimizerTools } from "./tools/query-optimizer.js";
import { registerQueueBuilderTools } from "./tools/queue-builder.js";
import { registerRateLimiterTools } from "./tools/rate-limiter.js";
import { registerRbacForgeTools } from "./tools/rbac-forge.js";
import { registerReadmeGenTools } from "./tools/readme-gen.js";
import { registerRedisPatternsTools } from "./tools/redis-patterns.js";
import { registerRegexBuilderTools } from "./tools/regex-builder.js";
import { registerRestDesignerTools } from "./tools/rest-designer.js";
import { registerRetryPolicyTools } from "./tools/retry-policy.js";
import { registerRustCargoTools } from "./tools/rust-cargo.js";
import { registerS3ManagerTools } from "./tools/s3-manager.js";
import { registerSchemaDriftTools } from "./tools/schema-drift.js";
import { registerSdkGeneratorTools } from "./tools/sdk-generator.js";
import { registerSearchBuilderTools } from "./tools/search-builder.js";
import { registerSeedGenTools } from "./tools/seed-gen.js";
import { registerSendgridSetupTools } from "./tools/sendgrid-setup.js";
import { registerSeoAuditorTools } from "./tools/seo-auditor.js";
import { registerServerlessFrameworkTools } from "./tools/serverless-framework.js";
import { registerServiceScaffoldTools } from "./tools/service-scaffold.js";
import { registerSessionManagerTools } from "./tools/session-manager.js";
import { registerSlackBotTools } from "./tools/slack-bot.js";
import { registerSocialLoginTools } from "./tools/social-login.js";
import { registerSqlArmorTools } from "./tools/sql-armor.js";
import { registerStateManagerTools } from "./tools/state-manager.js";
import { registerStripeSetupTools } from "./tools/stripe-setup.js";
import { registerStructuredLogTools } from "./tools/structured-log.js";
import { registerTechDebtTrackerTools } from "./tools/tech-debt-tracker.js";
import { registerTerraformModuleTools } from "./tools/terraform-module.js";
import { registerTrpcSetupTools } from "./tools/trpc-setup.js";
import { registerTsconfigGenTools } from "./tools/tsconfig-gen.js";
import { registerTwoFactorTools } from "./tools/two-factor.js";
import { registerTypeStrengthenerTools } from "./tools/type-strengthener.js";
import { registerUnitTestGenTools } from "./tools/unit-test-gen.js";
import { registerUptimeSentinelTools } from "./tools/uptime-sentinel.js";
import { registerUsageMeteringTools } from "./tools/usage-metering.js";
import { registerViteConfigTools } from "./tools/vite-config.js";
import { registerWebhookBuilderTools } from "./tools/webhook-builder.js";
import { registerWebpackConfigTools } from "./tools/webpack-config.js";
import { registerWebsocketSetupTools } from "./tools/websocket-setup.js";
import { registerWinstonSetupTools } from "./tools/winston-setup.js";
import { registerWorkflowEngineTools } from "./tools/workflow-engine.js";
import { registerWorkspaceSetupTools } from "./tools/workspace-setup.js";

const server = new McpServer({
  name: "plugin-hub",
  version: "3.0.0",
});

registerA11yFixerTools(server);
registerAlertRulesTools(server);
registerApiDocsTools(server);
registerApiForgeTools(server);
registerApiKeyManagerTools(server);
registerArchitectureDocsTools(server);
registerAuditTrailTools(server);
registerAuthArchitectTools(server);
registerBatchJobTools(server);
registerBillingSystemTools(server);
registerBundleAnalyzerTools(server);
registerCacheArchitectTools(server);
registerChangelogGenTools(server);
registerCircuitBreakerTools(server);
registerCliBuilderTools(server);
registerCloudflareWorkerTools(server);
registerCodeSmellsTools(server);
registerCommitLinterTools(server);
registerComplexityReducerTools(server);
registerContainerGuardTools(server);
registerCostHawkTools(server);
registerCoverageAnalyzerTools(server);
registerCssOptimizerTools(server);
registerDataAnonymizerTools(server);
registerDataGenTools(server);
registerDataMapperTools(server);
registerDeadCodeTools(server);
registerDepShieldTools(server);
registerDevcontainerTools(server);
registerDisasterRecoveryTools(server);
registerDistributedTracingTools(server);
registerDockerComposeGenTools(server);
registerDotnetSetupTools(server);
registerDuplicationHunterTools(server);
registerDynamodbDesignerTools(server);
registerE2eScenarioTools(server);
registerEmailTemplateTools(server);
registerEntitlementTools(server);
registerEnvGuardianTools(server);
registerErrorBoundaryTools(server);
registerErrorTrackingTools(server);
registerEslintConfigTools(server);
registerEtlBuilderTools(server);
registerFeatureFlagTools(server);
registerFileStorageTools(server);
registerFlakyTestFinderTools(server);
registerFormBuilderTools(server);
registerGdprToolkitTools(server);
registerGitWorkflowTools(server);
registerGithubActionsGenTools(server);
registerGoScaffoldTools(server);
registerGraphqlBuilderTools(server);
registerGraphqlClientTools(server);
registerHelmChartTools(server);
registerHttpClientTools(server);
registerI18nExtractorTools(server);
registerIacScannerTools(server);
registerImagePipelineTools(server);
registerJavaSpringTools(server);
registerJobDashboardTools(server);
registerJobQueueTools(server);
registerJsonToTypesTools(server);
registerJsonTransformerTools(server);
registerJwtToolkitTools(server);
registerK8sManifestTools(server);
registerLambdaBuilderTools(server);
registerLogSleuthTools(server);
registerMakefileGenTools(server);
registerMonitoringStackTools(server);
registerMultiTenantTools(server);
registerNginxConfigTools(server);
registerNodeExpressTools(server);
registerNodeNestjsTools(server);
registerNotifyHubTools(server);
registerOauthSetupTools(server);
registerOpenapiCodegenTools(server);
registerOwaspCheckerTools(server);
registerPaginationGenTools(server);
registerPasskeySetupTools(server);
registerPerfPilotTools(server);
registerPinoSetupTools(server);
registerPipelineOpsTools(server);
registerPresignedUrlsTools(server);
registerPricingPageTools(server);
registerProjectInitTools(server);
registerProtobufGenTools(server);
registerPushNotificationTools(server);
registerPwaBuilderTools(server);
registerPythonDjangoTools(server);
registerPythonFastapiTools(server);
registerPythonSetupTools(server);
registerQueryOptimizerTools(server);
registerQueueBuilderTools(server);
registerRateLimiterTools(server);
registerRbacForgeTools(server);
registerReadmeGenTools(server);
registerRedisPatternsTools(server);
registerRegexBuilderTools(server);
registerRestDesignerTools(server);
registerRetryPolicyTools(server);
registerRustCargoTools(server);
registerS3ManagerTools(server);
registerSchemaDriftTools(server);
registerSdkGeneratorTools(server);
registerSearchBuilderTools(server);
registerSeedGenTools(server);
registerSendgridSetupTools(server);
registerSeoAuditorTools(server);
registerServerlessFrameworkTools(server);
registerServiceScaffoldTools(server);
registerSessionManagerTools(server);
registerSlackBotTools(server);
registerSocialLoginTools(server);
registerSqlArmorTools(server);
registerStateManagerTools(server);
registerStripeSetupTools(server);
registerStructuredLogTools(server);
registerTechDebtTrackerTools(server);
registerTerraformModuleTools(server);
registerTrpcSetupTools(server);
registerTsconfigGenTools(server);
registerTwoFactorTools(server);
registerTypeStrengthenerTools(server);
registerUnitTestGenTools(server);
registerUptimeSentinelTools(server);
registerUsageMeteringTools(server);
registerViteConfigTools(server);
registerWebhookBuilderTools(server);
registerWebpackConfigTools(server);
registerWebsocketSetupTools(server);
registerWinstonSetupTools(server);
registerWorkflowEngineTools(server);
registerWorkspaceSetupTools(server);

async function main() {
  const isHosted = process.env.PORT || process.env.MCPIZE;
  if (isHosted) {
    const port = parseInt(process.env.PORT || "8080", 10);
    const httpServer = createServer(async (req, res) => {
      if (req.method === "POST" && req.url === "/mcp") {
        const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
        res.setHeader("Content-Type", "application/json");
        await server.connect(transport);
        await transport.handleRequest(req, res);
      } else if (req.method === "GET" && (req.url === "/health" || req.url === "/ping")) {
        res.writeHead(200);
        res.end("ok");
      } else {
        res.writeHead(404);
        res.end("Not found");
      }
    });
    httpServer.listen(port, () => {
      console.log(`Plugin Hub MCP server listening on port ${port}`);
    });
  } else {
    const transport = new StdioServerTransport();
    await server.connect(transport);
  }
}

main().catch(console.error);
